create table if not exists public.activities (
    id bigint generated by default as identity primary key,

    source_file text not null,
    center_name text not null,
    branch text,

    day text not null,
    raw_day text not null,

    start_time text not null,
    end_time text,
    end_time_source text,
    raw_time text,

    name text not null,
    raw_name text not null,
    english_name text,

    instructor text,
    location text,

    target_audience text not null,
    min_age integer,
    max_age integer,

    capacity integer,
    level text,
    notes text,
    season text,
    valid_from text,

    source_language text not null,
    status text not null,

    created_at timestamptz not null default now()
);

alter table public.activities enable row level security;

grant usage on schema public to service_role;
grant select, insert, delete on table public.activities to service_role;
grant usage on sequence public.activities_id_seq to service_role;

create table if not exists public.external_sources (
    id bigint generated by default as identity primary key,
    name text not null,
    url text not null unique,
    source_type text not null default 'publuu',
    is_active boolean not null default true,
    last_content_hash text,
    last_synced_at timestamptz,
    last_status text not null default 'pending',
    last_error text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.external_sources enable row level security;

grant usage on schema public to service_role;
grant select, insert, update, delete on table public.external_sources to service_role;
grant usage on sequence public.external_sources_id_seq to service_role;