create table if not exists public.activities (
    id bigint generated by default as identity primary key,

    source_file text not null,
    center_name text not null,
    branch text,

    day text not null,
    raw_day text not null,

    start_time text not null,
    end_time text,
    end_time_source text,
    raw_time text,

    name text not null,
    raw_name text not null,
    english_name text,

    instructor text,
    location text,

    target_audience text not null,
    min_age integer,
    max_age integer,

    capacity integer,
    level text,
    notes text,
    season text,
    valid_from text,

    source_language text not null,
    status text not null,

    created_at timestamptz not null default now()
);

alter table public.activities enable row level security;

grant usage on schema public to service_role;
grant select, insert on table public.activities to service_role;
grant usage on sequence public.activities_id_seq to service_role;
